# Generated by Django 5.1 on 2024-08-31 15:53

import accounts.models
import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('email', models.EmailField(db_index=True, max_length=120, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('role', models.IntegerField(choices=[(1, 'Super Admin User'), (2, 'Normal User'), (3, 'Admin User')], default=2, verbose_name='Gender')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is SuperUser')),
            ],
            options={
                'verbose_name': 'User',
                'db_table': 'user',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['email', 'updated_at'], name='user_email_e31555_idx')],
            },
            managers=[
                ('objects', accounts.models.ActiveUserManager()),
                ('all_objects', accounts.models.ActiveObjectsManager()),
                ('all_delete_objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_group', models.TextField(default='ALL', verbose_name='Business Group List')),
                ('category', models.TextField(default='ALL', verbose_name='Category List')),
                ('business_unit', models.TextField(default='ALL', verbose_name='Business Unit List')),
                ('country', models.TextField(default='ALL', verbose_name='Country List')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_permission_ref', to=settings.AUTH_USER_MODEL, verbose_name='User Obj')),
            ],
            options={
                'verbose_name': 'UserPermission',
                'db_table': 'user_permission',
            },
        ),
    ]
